version: '3.1'

services:
  fastapi:
    container_name: proyect_sales_api_prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - prod.env
    environment:
      - PORT=8000